const ICONS = {
  moon: require('../../assets/icons/moon.png'),
  restaurantMarker: require('../../assets/icons/restaurant-marker.png'),
  clock: require('../../assets/icons/clock.png'),
  clockBrown: require('../../assets/icons/clock-brown.png'),
  location: require('../../assets/icons/location.png'),
  phone: require('../../assets/icons/phone.png'),
  leftArrow: require('../../assets/icons/left-arrow.png'),
  email: require('../../assets/icons/email.png'),
  closedEye: require('../../assets/icons/closed-eye.png'),
  openEye: require('../../assets/icons/open-eye.png'),
  phoneLightColor: require('../../assets/icons/phone-light-color.png'),
  myLocation: require('../../assets/icons/my-location.png'),
  search: require('../../assets/icons/search.png'),
  profile: require('../../assets/icons/profile.png'),
  plus: require('../../assets/icons/plus.png'),
  locationFilled: require('../../assets/icons/location-filled.png'),
  profilePrimary: require('../../assets/icons/profile-primary.png'),
  edit: require('../../assets/icons/edit.png'),
  addPicture: require('../../assets/icons/add-picture.png'),
  done: require('../../assets/icons/done.png'),
  trash: require('../../assets/icons/trash.png'),
  rightArrow: require('../../assets/icons/right-arrow.png'),
  profileBrown: require('../../assets/icons/profile-brown.png'),
  topArrow: require('../../assets/icons/top-arrow.png'),
  settings: require('../../assets/icons/settings.png'),
  list: require('../../assets/icons/list.png'),
  arrowDown: require('../../assets/icons/arrow-down.png'),
  GPS: require('../../assets/icons/gps.png'),
  rightArrowWhite: require('../../assets/icons/right-arrow-white.png'),
  close: require('../../assets/icons/close.png'),
  locationWhite: require('../../assets/icons/location-white.png'),
};

export {ICONS};
