import {RestaurantInfo} from '../RestaurantsGateway.interface';

export const RESTAURANTS: RestaurantInfo[] = [
  {
    restaurantId: '0',
    closingTime: new Date(),
    openingTime: new Date(),
    location: {latitude: 37.421083, longitude: -122.104},
    name: 'اسم المطعم',
    ownerName: 'عبد القادر',
    pictures: [
      'https://webgrowhub.com/wp-content/uploads/2020/12/photo-1552566626-52f8b828add9.jpg',
      'https://webgrowhub.com/wp-content/uploads/2020/12/photo-1552566626-52f8b828add9.jpg',
    ],
    ownerNumber: '07 98 98 09 75',
  },
  {
    restaurantId: '1',
    closingTime: new Date(),
    openingTime: new Date(),
    location: {latitude: 120, longitude: 124},
    name: 'اسم المطعم',
    ownerName: 'عبد القادر',
    pictures: [],
    ownerNumber: '07 98 98 09 75',
  },
  {
    restaurantId: '2',
    closingTime: new Date(),
    openingTime: new Date(),
    location: {latitude: 136, longitude: 130},
    name: 'اسم المطعم',
    ownerName: 'عبد القادر',
    pictures: [],
    ownerNumber: '07 98 98 09 75',
  },
  {
    restaurantId: '3',
    closingTime: new Date(),
    openingTime: new Date(),
    location: {latitude: 132, longitude: 123},
    name: 'اسم المطعم',
    ownerName: 'عبد القادر',
    pictures: [],
    ownerNumber: '07 98 98 09 75',
  },
  {
    restaurantId: '4',
    closingTime: new Date(),
    openingTime: new Date(),
    location: {latitude: 145, longitude: 140},
    name: 'اسم المطعم',
    ownerName: 'عبد القادر',
    pictures: [],
    ownerNumber: '07 98 98 09 75',
  },
  {
    restaurantId: '5',
    closingTime: new Date(),
    openingTime: new Date(),
    location: {latitude: 150, longitude: 141},
    name: 'اسم المطعم',
    ownerName: 'عبد القادر',
    pictures: [],
    ownerNumber: '07 98 98 09 75',
  },
  {
    restaurantId: '6',
    closingTime: new Date(),
    openingTime: new Date(),
    location: {latitude: 122, longitude: 149},
    name: 'اسم المطعم',
    ownerName: 'عبد القادر',
    pictures: [],
    ownerNumber: '07 98 98 09 75',
  },
  {
    restaurantId: '7',
    closingTime: new Date(),
    openingTime: new Date(),
    location: {latitude: 133, longitude: 144},
    name: 'اسم المطعم',
    ownerName: 'عبد القادر',
    pictures: [],
    ownerNumber: '07 98 98 09 75',
  },
];
